# Generated by Django 5.0.4 on 2024-04-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Members",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("date_birth", models.DateTimeField()),
                ("date_baptism", models.DateTimeField()),
                ("address", models.CharField(max_length=100)),
                ("cep", models.IntegerField(blank=True)),
            ],
        ),
    ]
