# Generated by Django 5.0.4 on 2024-04-19 20:31

import localflavor.br.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_alter_members_date_baptism_alter_members_date_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="members",
            name="cep",
            field=localflavor.br.models.BRPostalCodeField(blank=True, max_length=9),
        ),
    ]
