# Generated by Django 5.0.4 on 2024-04-24 23:09

import localflavor.br.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_alter_members_cep"),
    ]

    operations = [
        migrations.AlterField(
            model_name="members",
            name="address",
            field=models.CharField(max_length=100, verbose_name="ENDEREÇO"),
        ),
        migrations.AlterField(
            model_name="members",
            name="cep",
            field=localflavor.br.models.BRPostalCodeField(
                blank=True, max_length=9, verbose_name="CEP"
            ),
        ),
        migrations.AlterField(
            model_name="members",
            name="date_baptism",
            field=models.DateField(verbose_name="DATA DE BATÍSMO"),
        ),
        migrations.AlterField(
            model_name="members",
            name="date_birth",
            field=models.DateField(verbose_name="DATA DE NASCIMENTO"),
        ),
        migrations.AlterField(
            model_name="members",
            name="first_name",
            field=models.CharField(max_length=100, verbose_name="NOME"),
        ),
        migrations.AlterField(
            model_name="members",
            name="last_name",
            field=models.CharField(max_length=100, verbose_name="SOBRE NOME"),
        ),
    ]
