# Generated by Django 5.0.4 on 2024-06-04 21:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_members_address_alter_members_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='first_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$', 'Somente letras e espaços são permitidos.')], verbose_name='NOME'),
        ),
        migrations.AlterField(
            model_name='members',
            name='last_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$', 'Somente letras e espaços são permitidos.')], verbose_name='SOBRE NOME'),
        ),
    ]
